on:
  push:
  pull_request:
  schedule:
  - cron: 0 0 * * *  # midnight every day

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: vvm workflow

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Tox
      run: pip install tox wheel

    - name: Run Tox
      run: tox -e lint

  py36:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Tox
      run: pip install tox wheel

    - name: Run Tox
      run: tox -e py36

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  py37:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Tox
      run: pip install tox wheel

    - name: Run Tox
      run: tox -e py37

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  py38:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Tox
      run: pip install tox wheel

    - name: Run Tox
      run: tox -e py38

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  py39:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Tox
      run: pip install tox wheel

    - name: Run Tox
      run: tox -e py39

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
