on:
  push:
  pull_request:
  schedule:
  - cron: 0 0 * * *  # midnight every day

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: vvm workflow

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [["3.11", "311"]]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version[0] }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version[0] }}

    - name: Install Tox
      run: pip install tox wheel

    - name: Run Tox
      run: tox -e py${{ matrix.python-version[1] }}
